### PR TITLE
output better error messages when yaml parsing fails

### LINKED ISSUE #77: indicate clearly when there's a yaml parse error
Currently an error gets reported, but it's not always clear that the error comes from trying to parse the yaml file. Example:

`error: block sequence entries are not allowed in this context`

From this yaml file:
``` yaml
protocol: - foo
```

It should say something like:

`error parsing foo.protocols.yaml: block sequence entries are not allowed in this context`

@matthandlersux: I think you mentioned this somewhere, but I can't find it.

### PR DESCRIPTION
**Pull request by soenkehahn**
Fixes #77.

### CODE REVIEW

File: src/protocol/mod.rs [hunk 1]
```diff
@@ -222,11 +222,22 @@ impl Protocol {
...
-    pub fn load(executable_path: &Path) -> R<Vec<Protocol>> {
-        let file_contents = read_protocols_file(executable_path)?;
+    fn parse_protocols(file_contents: &str) -> R<Vec<Protocol>> {
         let yaml: Vec<Yaml> = YamlLoader::load_from_str(&file_contents)?;
         yaml.into_iter().map(Protocol::parse).collect()
     }
+
+    pub fn load(executable_path: &Path) -> R<Vec<Protocol>> {
+        let file_contents = read_protocols_file(executable_path)?;
+        let result = Protocol::parse_protocols(&file_contents).map_err(|error| {
```
Comment (matthandlersux) [inline src/protocol/mod.rs]: is it necessary to unwrap the result with `?`, assign it, and then rewrap with `Ok(result)` below?

File: tests/run.rs [hunk 2]
```diff
@@ -45,6 +50,50 @@ fn simple() -> R<()> {
...
+    fn wrong_types() -> R<()> {
+        let script = TempFile::write_temp_script("")?;
+        let result = test_run_check_protocols(
+            &script,
+            r##"
+                |protocol: 42
+            "##,
+        );
+        assert_eq!(
+            format!("{}", result.unwrap_err()),
```
Comment (matthandlersux) [inline tests/run.rs]: just curious, is this equivalent to `result.unwrap_err().to_string()`?

File: test-utils/src/lib.rs [hunk 3]
```diff
@@ -23,6 +23,7 @@ fn run(command: &str, args: Vec<&str>) -> R<()> {
     }
 }
 
+#[derive(Debug)]
```
Comment (matthandlersux) [inline test-utils/src/lib.rs]: i don't think you make use of this in this PR

File: src/protocol/mod.rs [hunk 4]
```diff
@@ -222,11 +222,22 @@ impl Protocol {
...
+            format!(
+                "error parsing {}: {}",
```
Comment (matthandlersux) [inline src/protocol/mod.rs]: i think if the message mentions YAML specifically it would be more clear, something like: `YAML parsing error in: {}`

File: tests/run.rs [hunk 5]
```diff
@@ -45,6 +50,50 @@ fn simple() -> R<()> {
...
+            format!(
+                "error parsing {}.protocols.yaml: expected: array, got: Integer(42)",
```
Comment (matthandlersux) [inline tests/run.rs]: if i'm reading it correctly, this is not a YAML mistake, it's a misuse of the library. it would be nice if the error message could clarify between the two, so that one tells me (essentially) "you made a YAML mistake" and the other tells me "you misread the `check-protocols` docs"

File: src/protocol/mod.rs (hunk 1 above)
Comment (soenkehahn) [reply src/protocol/mod.rs]: Yeah, it is. `map_err` returns a value of type `Result<Vec<Protocol>, String>`. The result of `load` is `R<Vec<Protocol>>` which expands to `Result<Vec<Protocol>, Box<std::error::Error>>`. The `?` implicitly converts the error with the `From` trait. So we need that.

What would work is this:

``` rust
Ok(Protocol::parse_protocols(&file_contents).map_err(|error| {
    format!(
        "error parsing {}: {}",
        add_extension(executable_path, "protocols.yaml").to_string_lossy(),
        error
    )
})?)
```

Would that be better?

File: src/protocol/mod.rs (hunk 4 above)
Comment (soenkehahn) [reply src/protocol/mod.rs]: The file name will always include the `.yaml` extension, that's why I thought it wouldn't be necessary. Do you still think this change would be useful?

File: test-utils/src/lib.rs (hunk 3 above)
Comment (soenkehahn) [reply test-utils/src/lib.rs]: Yes, removed.

File: tests/run.rs (hunk 2 above)
Comment (soenkehahn) [reply tests/run.rs]: Yes, it is. TIL. `format("{}", ...)` uses the `Display` trait, but `ToString` is automatically implemented for everything that implements `Display`. (https://doc.rust-lang.org/std/string/trait.ToString.html#tymethod.to_string)

File: tests/run.rs (hunk 5 above)
Comment (soenkehahn) [reply tests/run.rs]: Yeah, that's correct. I changed the error messages now, Are they better like that?

File: src/protocol/mod.rs [hunk 6]
```diff
@@ -224,8 +224,25 @@ impl Protocol {
...
+        let result = yaml
+            .into_iter()
+            .map(Protocol::parse)
+            .collect::<R<Vec<Protocol>>>()
+            .map_err(|error| {
+                format!(
+                    "unexpected type in {}: {}",
+                    add_extension(executable_path, "protocols.yaml").to_string_lossy(),
+                    error
+                )
```
Comment (soenkehahn) [inline src/protocol/mod.rs]: I want to still dry up the two `map_err` calls.

File: src/protocol/mod.rs (hunk 1 above)
Comment (matthandlersux) [reply src/protocol/mod.rs]: ah, implicits. hmm, i don't think that would be any better, i think this is always bound to happen when implicit stuff occurs (where some lines of code aren't immediately obvious). in my mind the ideal thing to see would be a more explicit conversion, like...

```rust
Protocol::parse_protocols(&file_contents).map_err(|error| {
    format!(
        "error parsing {}: {}",
        add_extension(executable_path, "protocols.yaml").to_string_lossy(),
        error
    ).to_boxed() // here
})
```
but that could just be my lack of experience with rust

File: tests/run.rs (hunk 5 above)
Comment (matthandlersux) [reply tests/run.rs]: yup 👍
